[images]
size_thumbnail_image_taxon = [220, 220]  # constant width on details site for occurrence images from inat.
resizing_size = [3440, 1440]  # set to none to disable resizing and reencoding quality
sizes = [[1200, 800], [288, 288], [120, 120], [80, 80], [48, 48], [32, 32], [72, 72],
    [96, 96], [432, 432], [566, 566]]
jpg_quality = 82

[plants]
filter_hidden = true
taxon_search_max_results = 50

[frontend.restrictions]
length_shortened_plant_name_for_tag = 25  # # keep in sync with frontend constant LENGTH_SHORTENED_PLANT_NAME_FOR_TAG

[paths]
path_photos = "/common/plants/photos"
path_deleted_photos = "/common/plants/photos/deleted"
path_pickled_ml_models = '/common/plants/pickled'
