"""Make taxon cols not nullable.

Revision ID: 05fa62eaa93e
Revises: 705e8c52dcc2
Create Date: 2023-02-28 20:10:51.530521
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "05fa62eaa93e"
down_revision = "705e8c52dcc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taxon", "genus", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "taxon", "family", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "taxon",
        "taxonomic_status",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.execute(
        "UPDATE public.taxon "
        "set name_published_in_year = 1900 "
        "where name_published_in_year is null;"
    )
    op.alter_column(
        "taxon", "name_published_in_year", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("taxon", "synonym", existing_type=sa.BOOLEAN(), nullable=False)
    op.execute(
        "UPDATE public.taxon "
        "set authors = 'unknown_migration' "
        "where authors is null;"
    )
    op.alter_column(
        "taxon", "authors", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column("taxon", "hybridgenus", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("taxon", "hybridgenus", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "taxon", "authors", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("taxon", "synonym", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "taxon", "name_published_in_year", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "taxon", "taxonomic_status", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "taxon", "family", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "taxon", "genus", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###
