"""Non nullable col 2.

Revision ID: 1b84384bae57
Revises: 604fb9ee5df6
Create Date: 2023-03-03 12:44:00.980369
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1b84384bae57"
down_revision = "604fb9ee5df6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pot",
        "shape_side",
        existing_type=postgresql.ENUM(
            "FLAT", "HIGH", "UNKNOWN", "VERY_FLAT", "VERY_HIGH", name="fbshapeside"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pot",
        "shape_side",
        existing_type=postgresql.ENUM(
            "FLAT", "HIGH", "UNKNOWN", "VERY_FLAT", "VERY_HIGH", name="fbshapeside"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
