"""Drop filename_previewimage.

Revision ID: 1c9aef3b43a5
Revises: a9180a2deedf
Create Date: 2023-03-11 22:18:19.274342
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c9aef3b43a5"
down_revision = "a9180a2deedf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plants", "filename_previewimage")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plants",
        sa.Column(
            "filename_previewimage",
            sa.VARCHAR(length=240),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
