"""Seed_planting.

Revision ID: 0a92aa948036
Revises: ff220d6054e4
Create Date: 2023-05-04 09:52:40.496832
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a92aa948036"
down_revision = "ff220d6054e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seed_planting",
        sa.Column(
            "id", sa.INTEGER(), sa.Identity(always=False, start=1, cycle=True), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("PLANTED", "GERMINATED", "ABANDONED", name="seedplantingstatus"),
            nullable=False,
        ),
        sa.Column("pollination_id", sa.INTEGER(), nullable=True),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column("sterilized", sa.BOOLEAN(), nullable=False),
        sa.Column("soaked", sa.BOOLEAN(), nullable=False),
        sa.Column("planted_on", sa.DATE(), nullable=False),
        sa.Column("germinated_first_on", sa.DATE(), nullable=True),
        sa.Column("count_planted", sa.INTEGER(), nullable=False),
        sa.Column("count_germinated", sa.INTEGER(), nullable=True),
        sa.Column("last_update_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creation_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pollination_id"],
            ["pollination.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seed_planting")
    # ### end Alembic commands ###
