"""Make plants.cancellation_date Date not Datetime.

Revision ID: fef47bc17b4e
Revises: b0647a7861e3
Create Date: 2023-03-03 16:34:15.319792
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fef47bc17b4e"
down_revision = "b0647a7861e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE plants ALTER COLUMN cancellation_date TYPE DATE;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
