"""Rename taxonoccimage's created_on to photographed_at.

Revision ID: 5ec48043f8b6
Revises: 813c5a16b867
Create Date: 2023-03-08 20:49:10.875815
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ec48043f8b6"
down_revision = "813c5a16b867"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE taxon_ocurrence_image RENAME created_on TO photographed_at;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
