"""Change varchar for keyword.

Revision ID: b2dbd040238b
Revises: 1057e4b949db
Create Date: 2023-03-03 18:21:26.140136
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b2dbd040238b"
down_revision = "1057e4b949db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("distribution", "name", existing_type=sa.VARCHAR(length=40), nullable=False)
    op.alter_column(
        "distribution",
        "establishment",
        existing_type=sa.VARCHAR(length=15),
        nullable=False,
    )
    op.alter_column(
        "distribution", "feature_id", existing_type=sa.VARCHAR(length=5), nullable=False
    )
    op.alter_column(
        "distribution", "tdwg_code", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column("distribution", "tdwg_level", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("distribution", "taxon_id", existing_type=sa.INTEGER(), nullable=False)
    op.execute("ALTER TABLE image_keywords ALTER COLUMN keyword TYPE varchar(60);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("distribution", "taxon_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("distribution", "tdwg_level", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("distribution", "tdwg_code", existing_type=sa.VARCHAR(length=10), nullable=True)
    op.alter_column("distribution", "feature_id", existing_type=sa.VARCHAR(length=5), nullable=True)
    op.alter_column(
        "distribution",
        "establishment",
        existing_type=sa.VARCHAR(length=15),
        nullable=True,
    )
    op.alter_column("distribution", "name", existing_type=sa.VARCHAR(length=40), nullable=True)
    # ### end Alembic commands ###
