"""Delete col Event.pot_id , add constraints.

Revision ID: 2e2f04c40820
Revises: 2ca6fbb407ac
Create Date: 2023-04-11 00:16:48.339191
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e2f04c40820"
down_revision = "2ca6fbb407ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("event_pot_id_fkey", "event", type_="foreignkey")
    op.drop_column("event", "pot_id")
    op.create_foreign_key(None, "pot", "event", ["event_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pot", type_="foreignkey")
    op.add_column("event", sa.Column("pot_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("event_pot_id_fkey", "event", "pot", ["pot_id"], ["id"])
    # ### end Alembic commands ###
