"""Distribution.establishment to enum.

Revision ID: 39d0d2e94967
Revises: 3fee69e7668e
Create Date: 2023-05-07 19:48:10.123253
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from plants.modules.taxon.enums import Establishment

# revision identifiers, used by Alembic.
revision = "39d0d2e94967"
down_revision = "3fee69e7668e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    florescencestatus = postgresql.ENUM(*Establishment.get_names(), name="establishment")
    florescencestatus.create(op.get_bind())

    op.execute("UPDATE distribution SET establishment = 'NATIVE' WHERE establishment = 'Native';")
    op.execute(
        "UPDATE distribution SET establishment = 'INTRODUCED' WHERE establishment = 'Introduced';"
    )
    op.execute(
        "ALTER TABLE distribution ALTER COLUMN establishment TYPE establishment USING establishment::establishment;"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
