"""More not nulls.

Revision ID: 820d728e74b5
Revises: 22988d916afd
Create Date: 2023-05-07 20:05:49.966885
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "820d728e74b5"
down_revision = "22988d916afd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tags", "text", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column(
        "tags",
        "state",
        existing_type=postgresql.ENUM(
            "NONE", "INDICATION01", "SUCCESS", "INFORMATION", "ERROR", "WARNING", name="tagstate"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tags",
        "state",
        existing_type=postgresql.ENUM(
            "NONE", "INDICATION01", "SUCCESS", "INFORMATION", "ERROR", "WARNING", name="tagstate"
        ),
        nullable=True,
    )
    op.alter_column("tags", "text", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###
