"""Context to enum in db pt2.

Revision ID: ff220d6054e4
Revises: 63ef5b81cf02
Create Date: 2023-04-11 20:45:25.287110
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff220d6054e4"
down_revision = "63ef5b81cf02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "UPDATE pollination SET last_update_context = 'API' WHERE last_update_context = 'api';"
    )
    op.execute(
        "UPDATE pollination SET last_update_context = 'MANUAL' WHERE last_update_context = 'manual';"
    )
    op.execute(
        "UPDATE pollination SET last_update_context = 'IMPORT' WHERE last_update_context = 'import';"
    )
    op.execute(
        "ALTER TABLE pollination ALTER COLUMN last_update_context TYPE context USING last_update_context::context;"
    )

    op.execute(
        "UPDATE pollination SET creation_at_context = 'API' WHERE creation_at_context = 'api';"
    )
    op.execute(
        "UPDATE pollination SET creation_at_context = 'MANUAL' WHERE creation_at_context = 'manual';"
    )
    op.execute(
        "UPDATE pollination SET creation_at_context = 'IMPORT' WHERE creation_at_context = 'import';"
    )
    op.execute(
        "ALTER TABLE pollination ALTER COLUMN creation_at_context TYPE context USING creation_at_context::context;"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
