"""New cols pollination.count_pollinated and count_capsules.

Revision ID: f0cbf3dc1779
Revises: 3fec819036fc
Create Date: 2023-04-09 14:11:53.290518
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0cbf3dc1779"
down_revision = "3fec819036fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pollination", sa.Column("count_pollinated", sa.INTEGER(), nullable=True))
    op.add_column("pollination", sa.Column("count_capsules", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pollination", "count_capsules")
    op.drop_column("pollination", "count_pollinated")
    # ### end Alembic commands ###
