"""Change date col.

Revision ID: b0647a7861e3
Revises: 953fad0c7547
Create Date: 2023-03-03 16:24:26.189116
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b0647a7861e3"
down_revision = "953fad0c7547"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE event ALTER COLUMN date TYPE varchar(10);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
