"""Seed_planting soil.

Revision ID: 03a8e23a10c9
Revises: 0a92aa948036
Create Date: 2023-05-05 21:08:22.223408
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03a8e23a10c9"
down_revision = "0a92aa948036"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM seed_planting")
    op.add_column("seed_planting", sa.Column("soil_id", sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, "seed_planting", "soil", ["soil_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "seed_planting", type_="foreignkey")
    op.drop_column("seed_planting", "soil_id")
    # ### end Alembic commands ###
