"""Rename florescence date cols.

Revision ID: dbfcf029737d
Revises: fef47bc17b4e
Create Date: 2023-03-03 16:43:35.307731
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dbfcf029737d"
down_revision = "fef47bc17b4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE florescence RENAME inflorescence_appearance_date TO inflorescence_appeared_at;"
    )
    op.execute(
        "ALTER TABLE florescence RENAME first_flower_opening_date TO first_flower_opened_at;"
    )
    op.execute("ALTER TABLE florescence RENAME last_flower_closing_date TO last_flower_closed_at;")
    #
    #


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
