"""Rename pollination.pollination_timestamp to pollinated_at.

Revision ID: 813c5a16b867
Revises: f169d45c0b86
Create Date: 2023-03-08 19:30:57.088080
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "813c5a16b867"
down_revision = "f169d45c0b86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE pollination RENAME pollination_timestamp TO pollinated_at;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
