"""Image.record_date_time tz aware.

Revision ID: f169d45c0b86
Revises: c7e0053ff184
Create Date: 2023-03-04 18:46:18.358095
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f169d45c0b86"
down_revision = "c7e0053ff184"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE image ALTER COLUMN record_date_time TYPE timestamp with time zone;"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
