"""Distribution.establishment to enum.

Revision ID: 3fee69e7668e
Revises: 23eaa0dca7e6
Create Date: 2023-05-07 19:47:26.371179
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3fee69e7668e"
down_revision = "23eaa0dca7e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tags", "plant_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tags", "plant_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
