"""Taxon enum cols.

Revision ID: 1acc6ba22b44
Revises: f7509236e341
Create Date: 2023-03-03 13:07:33.307646
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1acc6ba22b44"
down_revision = "f7509236e341"
branch_labels = None
depends_on = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql

    op.execute(
        "UPDATE taxon \
        SET custom_rank = (CASE \
            WHEN custom_rank = 'gen.' THEN 'GENUS' \
            WHEN custom_rank = 'spec.' THEN 'SPECIES' \
            WHEN custom_rank = 'subsp.' THEN 'SUBSPECIES' \
            WHEN custom_rank = 'var.' THEN 'VARIETY' \
            WHEN custom_rank = 'forma' THEN 'FORMA' \
         END);"
    )
    enum_new_type = postgresql.ENUM(
        "FORMA", "GENUS", "SPECIES", "SUBSPECIES", "VARIETY", name="fbrank"
    )
    enum_new_type.create(op.get_bind())
    op.execute(
        "ALTER TABLE taxon ALTER COLUMN custom_rank TYPE fbrank USING custom_rank::text::fbrank"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
