"""Pollination remove cols.

Revision ID: 23eaa0dca7e6
Revises: accd42d1acbf
Create Date: 2023-05-07 15:03:12.342148
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23eaa0dca7e6"
down_revision = "accd42d1acbf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pollination", "first_seeds_sown")
    op.drop_column("pollination", "first_seeds_germinated")
    op.drop_column("pollination", "days_until_first_germination")
    op.drop_column("pollination", "germination_rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pollination",
        sa.Column(
            "germination_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "pollination",
        sa.Column("days_until_first_germination", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pollination",
        sa.Column("first_seeds_germinated", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pollination",
        sa.Column("first_seeds_sown", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
