"""Undo.

Revision ID: bb20f26f5b7e
Revises: 43dd09460f0c
Create Date: 2023-04-10 13:04:21.825813
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb20f26f5b7e"
down_revision = "43dd09460f0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "image_to_event_association_event_id_fkey",
        "image_to_event_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "image_to_event_association",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "image_to_event_association", type_="foreignkey")
    op.create_foreign_key(
        "image_to_event_association_event_id_fkey",
        "image_to_event_association",
        "event",
        ["event_id"],
        ["id"],
    )
    # ### end Alembic commands ###
