"""Rename taxon_occurrence_image date to created_on.

Revision ID: 502609ab2a9a
Revises: dbfcf029737d
Create Date: 2023-03-03 17:10:04.151359
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "502609ab2a9a"
down_revision = "dbfcf029737d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE taxon_ocurrence_image RENAME date TO created_on;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
