"""Undo.

Revision ID: 0fe895aa4d93
Revises: c08ccdffdee7
Create Date: 2023-04-10 13:07:37.448376
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fe895aa4d93"
down_revision = "c08ccdffdee7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "image_to_event_association_event_id_fkey",
        "image_to_event_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "image_to_event_association_image_id_fkey",
        "image_to_event_association",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "image_to_event_association", "image", ["image_id"], ["id"])
    op.create_foreign_key(None, "image_to_event_association", "event", ["event_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "image_to_event_association", type_="foreignkey")
    op.drop_constraint(None, "image_to_event_association", type_="foreignkey")
    op.create_foreign_key(
        "image_to_event_association_image_id_fkey",
        "image_to_event_association",
        "image",
        ["image_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "image_to_event_association_event_id_fkey",
        "image_to_event_association",
        "event",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
