"""Drop observation.height and .stem_max_diameter.

Revision ID: 3c6e20643697
Revises: 3fa0140431d8
Create Date: 2023-11-18 20:14:00.233422
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6e20643697'
down_revision = '3fa0140431d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('florescence', 'avg_ripening_time')
    op.drop_column('observation', 'stem_max_diameter')
    op.drop_column('observation', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('height', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=True))
    op.add_column('observation', sa.Column('stem_max_diameter', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=True))
    op.add_column('florescence', sa.Column('avg_ripening_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
