"""Seed Planting abandoned_on  date.

Revision ID: ba4038a16c0f
Revises: 33ce9231b9dc
Create Date: 2023-11-11 17:37:34.708740
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4038a16c0f'
down_revision = '33ce9231b9dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed_planting', sa.Column('abandoned_on', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seed_planting', 'abandoned_on')
    # ### end Alembic commands ###
