"""Del phys col plant.self_pollinates.

Revision ID: 33ce9231b9dc
Revises: 167f4568b126
Create Date: 2023-05-15 22:08:22.480162
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33ce9231b9dc"
down_revision = "167f4568b126"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plants", "self_pollinates")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plants", sa.Column("self_pollinates", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
