"""Seed_planting to plant.

Revision ID: 96fd7a34439c
Revises: 03a8e23a10c9
Create Date: 2023-05-06 10:59:04.762213
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96fd7a34439c"
down_revision = "03a8e23a10c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plants", sa.Column("seed_planting_id", sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, "plants", "seed_planting", ["seed_planting_id"], ["id"])
    op.alter_column("seed_planting", "pollination_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("seed_planting", "pollination_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "plants", type_="foreignkey")
    op.drop_column("plants", "seed_planting_id")
    # ### end Alembic commands ###
