"""Add tag.taxon_id.

Revision ID: 82ce0c90900b
Revises: 3c6e20643697
Create Date: 2023-11-26 20:13:32.144415
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ce0c90900b'
down_revision = '3c6e20643697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('taxon_id', sa.INTEGER(), nullable=True))
    op.alter_column('tags', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'tags', 'taxon', ['taxon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.alter_column('tags', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tags', 'taxon_id')
    # ### end Alembic commands ###
