"""New col plant.self_pollinates.

Revision ID: 73935307fedf
Revises: 820d728e74b5
Create Date: 2023-05-15 21:44:38.809196
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73935307fedf"
down_revision = "820d728e74b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plants", sa.Column("self_pollinates", sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plants", "self_pollinates")
    # ### end Alembic commands ###
