"""increase max plant name in history

Revision ID: 993a5e2e80fd
Revises: baa3440dd7bb
Create Date: 2025-08-29 12:02:08.739809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993a5e2e80fd'
down_revision = 'baa3440dd7bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'plant_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'plant_name',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
