"""pollination count column

Revision ID: 20e1b5087385
Revises: 8b48dda8861b
Create Date: 2023-01-29 19:25:31.899394

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '20e1b5087385'
down_revision = '8b48dda8861b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pollination', sa.Column('count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pollination', 'count')
    # ### end Alembic commands ###
