"""deleted and active plant flags not nullable

Revision ID: 2e57fa06f44d
Revises: b944434abf76
Create Date: 2023-02-08 11:39:44.859939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e57fa06f44d'
down_revision = 'b944434abf76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('plants', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plants', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
