"""Migrate pot.shape_side to enum.

Revision ID: 4aebb2bed9bc
Revises: 8e2beb87d132
Create Date: 2023-03-03 12:01:34.560549
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4aebb2bed9bc"
down_revision = "8e2beb87d132"
branch_labels = None
depends_on = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql

    op.execute(
        "UPDATE pot \
        SET shape_side = (CASE \
            WHEN shape_side = 'very flat' THEN 'VERY_FLAT' \
            WHEN shape_side = 'flat' THEN 'FLAT' \
            WHEN shape_side = 'high' THEN 'HIGH' \
            WHEN shape_side = 'very high' THEN 'VERY_HIGH' \
         END);"
    )
    enum_new_type = postgresql.ENUM("FLAT", "HIGH", "VERY_FLAT", "VERY_HIGH", name="fbshapeside")
    enum_new_type.create(op.get_bind())
    op.execute(
        "ALTER TABLE pot ALTER COLUMN shape_side TYPE fbshapeside USING shape_side::text::fbshapeside"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
