"""Non nullable col.

Revision ID: 604fb9ee5df6
Revises: e67f125b3b21
Create Date: 2023-03-03 12:41:20.415434
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "604fb9ee5df6"
down_revision = "e67f125b3b21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    enum_new_type = postgresql.ENUM(
        "FLAT", "HIGH", "UNKNOWN", "VERY_FLAT", "VERY_HIGH", name="fbshapeside"
    )
    op.execute("ALTER TYPE fbshapeside RENAME TO fbshapeside_old")
    enum_new_type.create(op.get_bind())
    op.execute(
        "ALTER TABLE pot ALTER COLUMN shape_side TYPE fbshapeside USING shape_side::text::fbshapeside"
    )
    op.execute("DROP TYPE fbshapeside_old")

    op.execute("UPDATE pot SET shape_side = 'UNKNOWN' WHERE shape_side IS NULL;")
    op.alter_column(
        "pot",
        "shape_top",
        existing_type=postgresql.ENUM("HEXAGONAL", "OVAL", "ROUND", "SQUARE", name="fbshapetop"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pot",
        "shape_top",
        existing_type=postgresql.ENUM("HEXAGONAL", "OVAL", "ROUND", "SQUARE", name="fbshapetop"),
        nullable=True,
    )
    # ### end Alembic commands ###
