"""pollination: new col pollen_quality

Revision ID: 705e8c52dcc2
Revises: b58395e662ad
Create Date: 2023-02-18 12:49:54.518790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705e8c52dcc2'
down_revision = 'b58395e662ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pollination', sa.Column('pollen_quality', sa.VARCHAR(length=10), nullable=True))
    op.execute("UPDATE pollination SET pollen_quality = 'unknown' WHERE pollen_quality is null;")
    op.execute("ALTER TABLE pollination ALTER pollen_quality SET NOT NULL;")




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pollination', 'pollen_quality')
    # ### end Alembic commands ###
