"""More non null cols.

Revision ID: 8e2beb87d132
Revises: 05fa62eaa93e
Create Date: 2023-03-01 14:23:31.222205
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8e2beb87d132"
down_revision = "05fa62eaa93e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "history",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column("history", "plant_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "history", "plant_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column("history", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "image", "relative_path", existing_type=sa.VARCHAR(length=240), nullable=False
    )
    op.alter_column("soil", "mix", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "taxon_ocurrence_image",
        "scientific_name",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "basis_of_record",
        existing_type=sa.VARCHAR(length=25),
        nullable=False,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "creator_identifier",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "references",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "href",
        existing_type=sa.VARCHAR(length=150),
        nullable=False,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "filename_thumbnail",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taxon_ocurrence_image",
        "filename_thumbnail",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "href",
        existing_type=sa.VARCHAR(length=150),
        nullable=True,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "references",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "creator_identifier",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "basis_of_record",
        existing_type=sa.VARCHAR(length=25),
        nullable=True,
    )
    op.alter_column(
        "taxon_ocurrence_image",
        "scientific_name",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column("soil", "mix", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "image", "relative_path", existing_type=sa.VARCHAR(length=240), nullable=True
    )
    op.alter_column("history", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "history", "plant_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("history", "plant_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "history",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###
