"""Initial Version

Revision ID: a916c5152b05
Revises:
Create Date: 2023-01-28 15:18:10.664558

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a916c5152b05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_category', 'sort')
    op.alter_column('soil', 'soil_name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    op.alter_column('taxon', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    op.execute("UPDATE taxon SET full_html_name = name WHERE full_html_name is null;")
    op.alter_column('taxon', 'full_html_name',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('taxon', 'is_custom',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('taxon', 'rank',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=False)
    op.alter_column('taxon', 'lsid',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('taxon', 'hybrid',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_column('taxon', 'powo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('powo_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('taxon', 'hybrid',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('taxon', 'lsid',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('taxon', 'rank',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('taxon', 'is_custom',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('taxon', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('soil', 'soil_name',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.add_column('property_category', sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
