"""add striped to colors enum

Revision ID: b58395e662ad
Revises: bbceddd14edc
Create Date: 2023-02-17 12:57:54.316694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58395e662ad'
down_revision = 'bbceddd14edc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE flowercolordifferentiation ADD VALUE 'STRIPED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
